<?php
if (!defined('APP_ROOT')) {
    $dir = __DIR__;
    for ($i = 0; $i < 10; $i++) {
        if (file_exists($dir . '/bootstrap.php')) {
            require $dir . '/bootstrap.php';
            break;
        }
        $parent = dirname($dir);
        if ($parent === $dir) break;
        $dir = $parent;
    }
}
$allowedRoles = [ROLE_ADMIN];
require APP_ROOT . '/app/middleware/RoleMiddleware/RoleMiddleware.php';

use App\Services\FirebaseService;
use App\Services\StudentService;

$format = strtolower(trim((string) ($_GET['format'] ?? 'pdf')));
if (!in_array($format, ['pdf'], true)) {
    http_response_code(400);
    exit('Unsupported finance export format.');
}

require_once APP_ROOT . '/fpdf19/fpdf.php';

if (!empty($_GET['paymentId'])) {
    $paymentId = trim((string) $_GET['paymentId']);
    $payment = null;
    $records = FirebaseService::getInstance()->getCollection(COL_FINANCE_PAYMENTS, [], 1000);
    foreach ($records as $record) {
        if ((string) ($record['id'] ?? '') === $paymentId) {
            $payment = $record;
            break;
        }
    }

    if (!$payment) {
        flash('error', 'Payment not found.');
        redirect(url('index.php?route=' . urlencode('/views/admin/finance/payments/index.php')));
    }

    $studentId = (string) ($payment['studentId'] ?? $payment['student_id'] ?? '');
    $student = StudentService::find($studentId);
    $studentName = trim((string) (($student['firstName'] ?? '') . ' ' . ($student['lastName'] ?? '')));

    $pdf = new FPDF();
    $pdf->AddPage();
    $pdf->SetFont('Arial', 'B', 16);
    $pdf->Cell(0, 10, 'Dormitory Payment Receipt', 0, 1, 'C');
    $pdf->Ln(4);

    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(50, 8, 'Receipt No:', 0, 0);
    $pdf->Cell(0, 8, (string) ($payment['reference'] ?? 'N/A'), 0, 1);
    $pdf->Cell(50, 8, 'Student:', 0, 0);
    $pdf->Cell(0, 8, $studentName !== '' ? $studentName : 'Student', 0, 1);
    $pdf->Cell(50, 8, 'Fee:', 0, 0);
    $pdf->Cell(0, 8, (string) ($payment['feeName'] ?? 'Boarding Fee'), 0, 1);
    $pdf->Cell(50, 8, 'Amount:', 0, 0);
    $pdf->Cell(0, 8, 'GHS ' . number_format((float) ($payment['amount'] ?? 0), 2), 0, 1);
    $pdf->Cell(50, 8, 'Method:', 0, 0);
    $pdf->Cell(0, 8, (string) ($payment['paymentMethod'] ?? 'Cash'), 0, 1);
    $pdf->Cell(50, 8, 'Status:', 0, 0);
    $pdf->Cell(0, 8, strtoupper((string) ($payment['status'] ?? 'paid')), 0, 1);
    $pdf->Cell(50, 8, 'Date:', 0, 0);
    $pdf->Cell(0, 8, date('d M Y', strtotime((string) ($payment['recordedAt'] ?? ($payment['createdAt'] ?? date('Y-m-d H:i:s'))))), 0, 1);
    $pdf->Ln(8);
    $pdf->Cell(0, 8, 'Generated by Dormitory Management System', 0, 1, 'C');
    $pdf->Output('D', 'payment-receipt-' . date('Y-m-d-His') . '.pdf');
    exit;
}

if (!empty($_GET['studentId'])) {
    $studentId = trim((string) $_GET['studentId']);
    $student = StudentService::find($studentId);
    if (!$student) {
        flash('error', 'Student not found.');
        redirect(url('index.php?route=' . urlencode('/views/admin/finance/payments/index.php')));
    }

    $studentName = trim((string) (($student['firstName'] ?? '') . ' ' . ($student['lastName'] ?? '')));
    $payments = [];
    foreach (FirebaseService::getInstance()->getCollection(COL_FINANCE_PAYMENTS, [], 1000) as $record) {
        if ((string) ($record['studentId'] ?? $record['student_id'] ?? '') === $studentId) {
            $payments[] = $record;
        }
    }

    $totalPaid = 0.0;
    foreach ($payments as $payment) {
        $totalPaid += (float) ($payment['amount'] ?? 0);
    }

    $pdf = new FPDF();
    $pdf->AddPage();
    $pdf->SetFont('Arial', 'B', 16);
    $pdf->Cell(0, 10, 'Student Finance Statement', 0, 1, 'C');
    $pdf->Ln(4);

    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(50, 8, 'Student:', 0, 0);
    $pdf->Cell(0, 8, $studentName !== '' ? $studentName : $studentId, 0, 1);
    $pdf->Cell(50, 8, 'Total Charges:', 0, 0);
    $pdf->Cell(0, 8, 'GHS 650.00', 0, 1);
    $pdf->Cell(50, 8, 'Total Paid:', 0, 0);
    $pdf->Cell(0, 8, 'GHS ' . number_format($totalPaid, 2), 0, 1);
    $pdf->Cell(50, 8, 'Outstanding:', 0, 0);
    $pdf->Cell(0, 8, 'GHS ' . number_format(max(0.0, 650.0 - $totalPaid), 2), 0, 1);
    $pdf->Ln(8);

    $pdf->SetFont('Arial', 'B', 10);
    $pdf->Cell(30, 8, 'Date', 1, 0, 'C');
    $pdf->Cell(55, 8, 'Fee', 1, 0, 'C');
    $pdf->Cell(30, 8, 'Amount', 1, 0, 'C');
    $pdf->Cell(35, 8, 'Method', 1, 0, 'C');
    $pdf->Cell(40, 8, 'Reference', 1, 1, 'C');

    $pdf->SetFont('Arial', '', 9);
    foreach ($payments as $payment) {
        $pdf->Cell(30, 7, date('d M Y', strtotime((string) ($payment['recordedAt'] ?? ($payment['createdAt'] ?? date('Y-m-d H:i:s'))))), 1, 0);
        $pdf->Cell(55, 7, substr((string) ($payment['feeName'] ?? 'Boarding Fee'), 0, 20), 1, 0);
        $pdf->Cell(30, 7, 'GHS ' . number_format((float) ($payment['amount'] ?? 0), 2), 1, 0);
        $pdf->Cell(35, 7, substr((string) ($payment['paymentMethod'] ?? 'Cash'), 0, 15), 1, 0);
        $pdf->Cell(40, 7, substr((string) ($payment['reference'] ?? 'N/A'), 0, 18), 1, 1);
    }

    if (empty($payments)) {
        $pdf->Cell(190, 8, 'No payments recorded for this student.', 1, 1, 'C');
    }

    $pdf->Output('D', 'student-statement-' . date('Y-m-d-His') . '.pdf');
    exit;
}

flash('error', 'No finance export target specified.');
redirect(url('index.php?route=' . urlencode('/views/admin/finance/payments/index.php')));
